app:
  mysql:
    host: localhost
    user: root
    password: Silencer&&55
    database: express-crud
    connectionLimit: 10
    queueLimit: 0

  auth:
    token-secret: ZGltYWdlc2hhcmUtbGVnYWN5LWJhY2tlbmQtcHJvamVjdA==
    token-expiration-msec: 360000