app:
  mysql:
    host: localhost
    user: root
    password: Silencer&&55
    database: express-crud
    connectionLimit: 10
    queueLimit: 0

  auth:
    token_secret: ZGltYWdlc2hhcmUtbGVnYWN5LWJhY2tlbmQtcHJvamVjdA==
    token_expiration_msec: 360000